"use client";

import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import LivePreview from "@/components/builder/LivePreview";

interface InsightsVisualData {
  profilePictureUrl: string | null;
  bannerUrl: string | null;
  topPosts: Array<{ image_url?: string }>;
}

function BuilderPopupInner() {
  const searchParams = useSearchParams();

  const initialTemplate = searchParams.get("template") || "Template";
  const initialTheme = searchParams.get("theme") || "xai3";
  const initialPrompt = searchParams.get("prompt") || "";
  const storeSlug = searchParams.get("store") || "";

  const [prompt, setPrompt] = useState(initialPrompt);
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [includeXImages, setIncludeXImages] = useState(true);
  const [visuals, setVisuals] = useState<InsightsVisualData | null>(null);

  const [editRequest, setEditRequest] = useState("");
  const [aiSuggestion, setAiSuggestion] = useState("");
  const [aiLoading, setAiLoading] = useState(false);

  const [saveLabel, setSaveLabel] = useState(`${initialTemplate} Draft`);
  const [saving, setSaving] = useState(false);
  const [savedMsg, setSavedMsg] = useState("");

  const autoGenerated = useRef(false);

  const postImageSummary = useMemo(() => {
    if (!visuals) return "not available";
    const urls = visuals.topPosts
      .map((post) => post.image_url)
      .filter((url): url is string => !!url)
      .slice(0, 4);
    return urls.length > 0 ? urls.join(", ") : "not available";
  }, [visuals]);

  useEffect(() => {
    let active = true;

    async function loadVisuals() {
      try {
        const res = await fetch("/api/console/insights", { cache: "no-store" });
        if (!res.ok) return;
        const data = await res.json();
        if (!active) return;

        setVisuals({
          profilePictureUrl: data.profilePictureUrl ?? null,
          bannerUrl: data.bannerUrl ?? null,
          topPosts: Array.isArray(data.topPosts) ? data.topPosts : [],
        });
      } catch {
        // Non-critical enhancement only.
      }
    }

    void loadVisuals();

    return () => {
      active = false;
    };
  }, []);

  const buildPromptWithImages = useCallback((basePrompt: string) => {
    if (!includeXImages || !visuals) return basePrompt;

    return [
      basePrompt,
      "",
      "Use these creator X images as visual references when generating this section:",
      `- Profile image: ${visuals.profilePictureUrl || "not available"}`,
      `- Banner image: ${visuals.bannerUrl || "not available"}`,
      `- Top post images: ${postImageSummary}`,
      "If an image URL is unavailable, continue without it.",
    ].join("\n");
  }, [includeXImages, postImageSummary, visuals]);

  const streamChat = useCallback(async (message: string, onChunk: (text: string) => void) => {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ message, theme: initialTheme }),
    });

    if (res.status === 429) {
      throw new Error("Rate limit reached. Try again in an hour.");
    }

    if (!res.ok || !res.body) {
      throw new Error("Request failed.");
    }

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let accumulated = "";

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      accumulated += decoder.decode(value, { stream: true });
      onChunk(accumulated);
    }
  }, [initialTheme]);

  const generateFromPrompt = useCallback(async (currentPrompt: string) => {
    if (!currentPrompt.trim()) return;

    setLoading(true);
    setError("");
    setResult("");

    try {
      const message = buildPromptWithImages(currentPrompt);
      await streamChat(message, setResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not generate component.");
    } finally {
      setLoading(false);
    }
  }, [buildPromptWithImages, streamChat]);

  async function generatePromptSuggestion() {
    if (!editRequest.trim()) return;

    setAiLoading(true);
    setAiSuggestion("");

    const coachPrompt = [
      "You rewrite storefront section prompts for RareImagery creators.",
      `Current theme: ${initialTheme}.`,
      "Return only an improved prompt with no markdown formatting.",
      `Current prompt: ${prompt || "none"}`,
      `Requested edits: ${editRequest}`,
    ].join("\n\n");

    try {
      await streamChat(coachPrompt, setAiSuggestion);
    } catch (err) {
      setAiSuggestion(err instanceof Error ? err.message : "Could not generate suggestion.");
    } finally {
      setAiLoading(false);
    }
  }

  async function applySuggestionAndRegenerate() {
    const nextPrompt = aiSuggestion.trim();
    if (!nextPrompt) return;

    setPrompt(nextPrompt);
    await generateFromPrompt(nextPrompt);
  }

  async function handleSave() {
    if (!result.trim() || !saveLabel.trim()) return;

    setSaving(true);
    setSavedMsg("");

    try {
      const res = await fetch("/api/builds", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ label: saveLabel.trim(), code: result }),
      });

      if (res.ok) {
        setSavedMsg("Build saved successfully.");
        if (window.opener && !window.opener.closed) {
          window.opener.postMessage(
            {
              type: "ri-builder-build-saved",
              label: saveLabel.trim(),
            },
            window.location.origin
          );
        }
        setTimeout(() => setSavedMsg(""), 2500);
      } else {
        setSavedMsg("Could not save build.");
      }
    } finally {
      setSaving(false);
    }
  }

  useEffect(() => {
    setPrompt(initialPrompt);
    setSaveLabel(`${initialTemplate} Draft`);
    autoGenerated.current = false;
  }, [initialPrompt, initialTemplate]);

  useEffect(() => {
    if (!initialPrompt.trim()) return;
    if (autoGenerated.current) return;

    autoGenerated.current = true;
    void generateFromPrompt(initialPrompt);
  }, [generateFromPrompt, initialPrompt]);

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      <div className="mx-auto max-w-[1500px] p-4 md:p-6">
        <div className="mb-4 rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <p className="text-xs uppercase tracking-[0.16em] text-zinc-400">Template Workspace</p>
              <h1 className="text-xl font-semibold">{initialTemplate}</h1>
              <p className="text-xs text-zinc-400">Theme: <span className="text-indigo-300">{initialTheme}</span></p>
            </div>
            <div className="flex items-center gap-2">
              {storeSlug && (
                <a
                  href={`/stores/${storeSlug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex min-h-10 items-center rounded-md border border-zinc-700 px-3 py-2 text-xs text-zinc-300 hover:border-zinc-500 hover:text-white"
                >
                  Open Live Store
                </a>
              )}
              <button
                onClick={() => window.close()}
                className="inline-flex min-h-10 items-center rounded-md border border-zinc-700 px-3 py-2 text-xs text-zinc-300 hover:border-zinc-500 hover:text-white"
              >
                Close
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.05fr_1.35fr]">
          <section className="space-y-4">
            <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4">
              <div className="mb-3 flex items-center justify-between gap-3">
                <h2 className="text-sm font-semibold">Prompt</h2>
                <button
                  onClick={() => void generateFromPrompt(prompt)}
                  disabled={loading || !prompt.trim()}
                  className="min-h-9 rounded-md bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-indigo-500 disabled:opacity-50"
                >
                  {loading ? "Generating..." : "Generate"}
                </button>
              </div>

              <textarea
                className="h-36 w-full resize-none rounded-lg border border-zinc-700 bg-zinc-800 p-3 text-sm text-white placeholder-zinc-500 focus:border-indigo-500 focus:outline-none"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe the storefront section..."
              />

              <label className="mt-3 flex items-center justify-between gap-2 rounded-lg border border-zinc-800 bg-zinc-950/70 p-3 text-xs text-zinc-300">
                <span>Use images from my X profile</span>
                <input
                  type="checkbox"
                  checked={includeXImages}
                  onChange={(e) => setIncludeXImages(e.target.checked)}
                  className="h-4 w-4 rounded border-zinc-600 bg-zinc-800 text-indigo-500"
                />
              </label>

              {error && <p className="mt-2 text-xs text-red-400">{error}</p>}
            </div>

            <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4">
              <h2 className="mb-3 text-sm font-semibold">AI Edit Box</h2>
              <textarea
                className="h-24 w-full resize-none rounded-lg border border-zinc-700 bg-zinc-800 p-3 text-sm text-white placeholder-zinc-500 focus:border-indigo-500 focus:outline-none"
                value={editRequest}
                onChange={(e) => setEditRequest(e.target.value)}
                placeholder="Tell AI what to change: tone, sections, copy, hierarchy..."
              />
              <div className="mt-3 flex flex-wrap gap-2">
                <button
                  onClick={() => void generatePromptSuggestion()}
                  disabled={aiLoading || !editRequest.trim()}
                  className="min-h-9 rounded-md bg-zinc-700 px-3 py-1.5 text-xs text-white transition hover:bg-zinc-600 disabled:opacity-50"
                >
                  {aiLoading ? "Thinking..." : "Suggest Prompt Update"}
                </button>
                <button
                  onClick={() => void applySuggestionAndRegenerate()}
                  disabled={!aiSuggestion.trim() || aiLoading}
                  className="min-h-9 rounded-md border border-indigo-500/60 px-3 py-1.5 text-xs text-indigo-200 transition hover:border-indigo-400 hover:text-indigo-100 disabled:opacity-40"
                >
                  Apply + Regenerate
                </button>
              </div>

              {aiSuggestion && (
                <pre className="mt-3 max-h-56 overflow-auto whitespace-pre-wrap rounded-lg border border-zinc-800 bg-zinc-950 p-3 text-xs text-zinc-300">
                  {aiSuggestion}
                </pre>
              )}
            </div>

            <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4">
              <h2 className="mb-3 text-sm font-semibold">Save Build</h2>
              <div className="flex flex-wrap gap-2">
                <input
                  value={saveLabel}
                  onChange={(e) => setSaveLabel(e.target.value)}
                  placeholder="Name this build"
                  className="min-h-10 flex-1 rounded-md border border-zinc-700 bg-zinc-800 px-3 text-sm text-white placeholder-zinc-500 focus:border-indigo-500 focus:outline-none"
                />
                <button
                  onClick={() => void handleSave()}
                  disabled={saving || !result.trim() || !saveLabel.trim()}
                  className="min-h-10 rounded-md bg-indigo-600 px-4 text-sm font-medium text-white transition hover:bg-indigo-500 disabled:opacity-50"
                >
                  {saving ? "Saving..." : "Save"}
                </button>
              </div>
              {savedMsg && <p className="mt-2 text-xs text-green-400">{savedMsg}</p>}
            </div>
          </section>

          <section className="space-y-4">
            <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/50">
              <div className="border-b border-zinc-800 px-4 py-2.5">
                <h2 className="text-sm font-semibold">Live Preview</h2>
              </div>
              <div className="bg-zinc-950">
                <LivePreview code={result} />
              </div>
            </div>

            <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-4">
              <div className="mb-2 flex items-center justify-between">
                <h2 className="text-sm font-semibold">Generated Code</h2>
                <button
                  onClick={() => navigator.clipboard.writeText(result)}
                  disabled={!result}
                  className="rounded-md border border-zinc-700 px-2.5 py-1 text-xs text-zinc-300 transition hover:border-zinc-500 hover:text-white disabled:opacity-40"
                >
                  Copy
                </button>
              </div>
              <pre className="max-h-[420px] overflow-auto whitespace-pre-wrap rounded-lg border border-zinc-800 bg-zinc-950 p-3 text-xs text-zinc-300">
                {result || "Generate a section to see code here."}
              </pre>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

export default function BuilderPopupPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-zinc-950 p-6 text-sm text-zinc-400">Loading builder workspace...</div>}>
      <BuilderPopupInner />
    </Suspense>
  );
}
